services:
  bot:
    image: ghcr.io/enthusiasm-c/notaai:sha-37dc12a3239916f437d292fd9e08d1a6170e9451
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
