services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
