services:
  bot:
    image: ghcr.io/enthusiasm-c/notaai:sha-6b6d1ce86dd2650f8cf6f6a262952d415e4b66cf
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
