services:
  bot:
    image: ghcr.io/enthusiasm-c/notaai:sha-52da199c21c158cdee11633111fecc00218482bd
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
