version: "3.9"

services:
  bot:
    image: ghcr.io/enthusiasm-c/notaai:sha-db310233c93d116557d3a51ba4982990bd531124
    env_file:
      - .env
    ports:
      - "8080:8080"     # health-check endpoint
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

