services:
  bot:
    build:
      context: .          # корень репозитория, где лежит Dockerfile
      dockerfile: Dockerfile
      args:
        - PIP_NO_CACHE_DIR=1
    image: notaai/bot:dev
    restart: unless-stopped

    # путь к вашему .env — абсолютный!
    env_file:
      - /root/.env        # ← поменяйте, если .env лежит в другом месте

    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
